name: Compile and upload
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: lukepereira/latex-action@master
        with:
          root_file: templates/main.tex
