name: Compile and upload
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: lukepereira/latex-action@master
        with:
          working_directory: templates/
          root_file: main.tex
      - name: upload artifact (debug)
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: templates/main.pdf